### ISSUE TITLE
MagoNatDE_i.h file not found in clean StaticDE builds

### ISSUE THREAD

**Issue by buggins** [rainers/mago#11]
#include "MagoNatDE_i.h" in MagoNatDE/Engine.h cannot be included if you build "Debug StaticDE" configuration from scratch.

As a workaround, it's possible to build "Debug" configuration first to generate _i.h file, then building of "Debug StaticDE" works ok.

**Comment by rainers** [comment]
I've committed a fix that changes the include path from `$(OutDir)MagoNatDE;` to `$(OutDir)..\$(Configuration) StaticDE\MagoNatDE;`. A bit ugly, but should work.
