### ISSUE TITLE
Mago-mi Numchild and type output seem to be switched in -var-create.

### ISSUE THREAD

**Issue by pirocks** [rainers/mago#16]
When a variable is created using -var-create I get the following output:
`[name: "var76", numchild: "char[][]", value: "{length=1 ptr=0x0019FE1C}", type: "0"]`
It seems that `numchild` should be `0`, while type should be `char[][]`.

**Comment by andre2007** [comment]
This issue can also be closed. The error does not occur anymore:
```
21:26:39.839 8> -var-create --thread 17172 --frame 0 - @ args
21:26:39.839 9> -var-create --thread 17172 --frame 0 - @ test
21:26:39.876 <8 [immediate] done: [name: "var1", numchild: "0", value: "{length=1 ptr=0x0019fe74}", type: "const(char)[][]"]
21:26:39.897 <9 [immediate] done: [name: "var2", numchild: "0", value: "{length=4267213 ptr=0x00000000}", type: "const(char)[][]"]
```

**Comment by rainers** [comment]
> This issue can also be closed. The error does not occur anymore:

Good.
