### ISSUE TITLE
Mago usage in IntelliJ

### ISSUE THREAD

**Issue by andre2007** [rainers/mago#17]
As far as I understand Mago provides a subset of GDB commands to enable IDEs to use Mago as replacement of GDB. 

I just tried Mago in IntelliJ and it seems there is an issue. As I do not have much GDB / Mago experience I cannot judge whether it is an issue with the D Language plugin for IntelliJ or maybe s.th. is missing in Mago. It would be great if you could have a look.

IntelliJ provides following information while trying to debug a simple hello world application:

**Console**
1^done,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="<PENDING>",file="app.d",fullname="C:/D/projects/magotest/source/app.d",line="6",pending="-f C:/D/projects/magotest/source/app.d:6",thread-groups=["i1"],times="0",original-location="C:/D/projects/magotest/source/app.d:6"}
2^done,features=["frozen - varobjs","pending - breakpoints","thread-info"]
3^error,msg="unknown command: 3file C:/D/projects/magotest/magotest.exe",code="undefined-command"
4^error,msg="Executable is not specified. Use file or exec-file command."

**GDB console**
19:54:46.503 0> C:\D\tools\mago-mi.exe --interpreter=mi2
19:54:46.527 1> -break-insert -f C:/D/projects/magotest/source/app.d:6
19:54:46.632 < [notify] thread-group-added: [id: "i1"]
GNU gdb (mago-mi 0.3.3) 7.1.90
"(Actually it's mago-mi debugger. Version shows GDB for Eclipse CDT compatibility)
"19:54:46.695 2> -list-features
19:54:46.695 3> file C:/D/projects/magotest/magotest.exe
19:54:46.695 4> run

**GDB Raw output**
=thread-group-added,id="i1"
~"GNU gdb (mago-mi 0.3.3) 7.1.90\n"
~"(Actually it's mago-mi debugger. Version shows GDB for Eclipse CDT compatibility)\n"
(gdb) 
@1^done,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="<PENDING>",file="app.d",fullname="C:/D/projects/magotest/source/app.d",line="6",pending="-f C:/D/projects/magotest/source/app.d:6",thread-groups=["i1"],times="0",original-location="C:/D/projects/magotest/source/app.d:6"}
(gdb) 
@2^done,features=["frozen - varobjs","pending - breakpoints","thread-info"]
(gdb) 
@3^error,msg="unknown command: 3file C:/D/projects/magotest/magotest.exe",code="undefined-command"
(gdb) 
@4^error,msg="Executable is not specified. Use file or exec-file command."
(gdb)

**Comment by andre2007** [comment]
I am not 100% sure but I think MagoMI expects the executable file as argument (--exec filePath) while IntelliJ passes the executable using GDB command "file" which isn't supported by MagoMI.

If my assumption is correct, what is your preferred solution?
- Asking the IntelliJ D Language developers to pass the executable as argument
- Enabling the file command in MagoMI

**Comment by rainers** [comment]
mago-mi is a spin-off created by @buggins and I know very little about it. I guess he can answer your questions better than I do.

**Comment by andre2007** [comment]
I compared with GDB mi2. Gdb knows the command file while MagoMI does not recognize it. But as MagoMI knows command "-file-exec-and-symbols" which is working fine, I close this issue.
