### ISSUE TITLE
Mago/Mago-Mi: On some windows systems debugging x86_64 does not work

### ISSUE THREAD

**Issue by andre2007** [rainers/mago#25]
I have this sample application:
```
import std.stdio;

void main(string[] args)

{
    writeln(args);
}
```
Which I compile with different architectures:
dub --arch x86
dub --arch x86_mscoff
dub --arch x86_64

On my pc A I am able to load the executable in Mago-Mi for all architecture
```
C:\D\tools\mago-mi.exe --interpreter=mi2
-file-exec-and-symbols C:/D/projects/testapp/testapp.exe
```

On pc B only architecture x86 and x86_mscoff is working. While execute the command "-file-exec-and-symbols C:/D/projects/testapp/testapp.exe" for the x86_64 architecture there is an error message

Launch failed. Result=-2147024894
Located here

https://github.com/rainers/mago/blob/master/MagoMI/mago-mi/source/MIEngine.cpp#L535

https://github.com/rainers/mago/blob/master/MagoMI/mago-mi/source/debugger.cpp#L876

I assume the issue is not DMD version related as I tried different version on my pc A and everyone is working. PC A has a windows build 1803 while pc B has 1709. Unfortunately I cannot install Visual Studio on PC B to test whether debugging of x86_64 fails there too.

**Comment by rainers** [comment]
I suspect you have Visual D installed on one PC, but not the other?

I guess you need MagoRemote.exe on PC B and linked to in the registry at

HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\MagoDebugger
value Remote_x64, e.g. "C:\Program Files (x86)\VisualD\Mago\MagoRemote.exe"

**Comment by andre2007** [comment]
At the moment I cannot test it but I am pretty sure that is the reason. On pc A where debugging x86_64 is working I removed the regedit key and I get the same result as on pc B.

I would like to add an output to Mago-Mi which gives a hint if a X86_64 is tried to debug and MagoRemote isn't setup correctly. There are 2 possibilities:

Option 1) Mago-Mi checks whether an executable is of x86_64 architecture and a regedit key exists pointing to a file "MagoRemote.exe" which should exists on file system. If this pre-requisites are not meet, an error message is shown.

Option 2) Mago could provide a method "GetLastErrorText" which Mago-Mi could call after launch failed. In case of the missing regedit/Mago-Remote.exe this method could provide an error text "Mago-Remote.exe isn't setup correctly".

Just a small hint within Mago-Mi would be sufficient to point into the right direction

**Comment by andre2007** [comment]
Maybe Mago-Mi could also be enhanced.  I would like to call mago-mi like:

```mago-mi install path/to/MagoRemote.exe```

This command would create the regedit key

```mago-mi uninstall```

This command would uninstall the regedit key.

**Comment by rainers** [comment]
If launching the debuggee fails, can't you just provide an appropriate message with the error status?

Usually mago is run with the users credentials, so it cannot modify this registry key.

Providing the path to MagoRemote.exe via registry key is not set in stone. It is useful for the debug engine that plugs into VS, because it is run from different locations. mago-mi.exe could just try to run it from its own directory (see `StartAgent` in RemoteDebuggerProxy.cpp).

**Comment by andre2007** [comment]
I had the chance to test it on PC B. I installed VisualD on top of Visual Studio Build Tools 2017 - 15.5.7
to have everything setup correctly.
While the executable is now loaded for all 3 architectures, loading the symbols only works for X86 (OMF).
For x86_mscoff and x86_64 no symbols are loaded:

**dub build --arch=x86_64**
=library-loaded,id="debug.exe",target-name="debug.exe",host-name="debug.exe",symbols-loaded="0",thread-group-id="i1"
=library-loaded,id="ntdll.dll",target-name="ntdll.dll",host-name="ntdll.dll",symbols-loaded="0",thread-group-id="i1"
=library-loaded,id="kernel32.dll",target-name="kernel32.dll",host-name="kernel32.dll",symbols-loaded="0",thread-group-id="i1"
...

**dub build --arch=x86_mscoff**
=library-loaded,id="debug.exe",target-name="debug.exe",host-name="debug.exe",symbols-loaded="0",thread-group-id="i1"
=library-loaded,id="ntdll.dll",target-name="ntdll.dll",host-name="ntdll.dll",symbols-loaded="0",thread-group-id="i1"
=library-loaded,id="kernel32.dll",target-name="kernel32.dll",host-name="kernel32.dll",symbols-loaded="0",thread-group-id="i1"
...

**dub build --arch=x86**
=library-loaded,id="debug.exe",target-name="debug.exe",host-name="debug.exe",symbols-loaded="1",thread-group-id="i1"
=library-loaded,id="ntdll.dll",target-name="ntdll.dll",host-name="ntdll.dll",symbols-loaded="0",thread-group-id="i1"
=library-loaded,id="kernel32.dll",target-name="kernel32.dll",host-name="kernel32.dll",symbols-loaded="0",thread-group-id="i1"
...

On pc B Visual Studio Build Tools 2017 - 15.5.7 is installed with following configuration:
```
  Visual C++ build tools
    Visual C+ Build Tools core features
    VC++ 2017 v141 toolset (x86,x64)
    Visual C++ 2017 Redistributable Update
  Windows 10 SDK
  Visual C++ tools for CMake
```

**Comment by rainers** [comment]
I suspect `PDBDebugStore::InitDebugInfo` fails to create a symbol provider via COM. It's usually implemented in a DLL like msdia140.dll. This is probably missing or not registered with the build tools.

**Comment by andre2007** [comment]
I found the file here: "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\DIA SDK\bin\amd64\msdia140.dll" and here (X86 ?) "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\DIA SDK\bin\msdia140.dll".

I try to find out whether it is registered. By chance do you know how to check this?

**Comment by rainers** [comment]
I think it has to be referenced form here:

HKEY_CLASSES_ROOT\CLSID\{e6756135-1e65-4d17-8576-610761398c3c}\InprocServer32

**Comment by andre2007** [comment]
Do you think it is possible to enhance the Mago setup routine:

- Include Mago-Mi
- Call regSvr32 for x86 / x86_64 dll in case Build Tools is found
- (OPTIONAL) add path containing mago-mi exe to PATH environment variable

The reason for the path environment variable is to enable IDEs to automatically find the location of mago-mi. But that would be some sugar on top.

As far as I know Mago-Mi is not only used in IntelliJ but also in Visual Studio Code. Providing a simple install routine would be great from an user experience perspective.

**Comment by rainers** [comment]
There is no "Mago setup" so far. I doubt it makes to add that to the Visual D setup, as the user has probably chosen an IDE other than Visual Studio.
I think this should rather be part of the respective installer for the IntelliJ/VS Code plugin.

**Comment by WebFreak001** [comment]
is Mago Remote and the registry key actually required?

I tried the regSvr32 command with the msdia140.dll, but an error pops up saying it was loaded but the call to "DllRegisterServer" failed with error code 0x80070005

I want to automate this and can't expect administrator access and would prefer not to write to registry, is there something that can be done to avoid this?

**Comment by rainers** [comment]
> is Mago Remote and the registry key actually required?

magoremote.exe is used to debug x64-processes with the mago debug engine. This is necessary in VS as VS is a 32-bit process.

I guess you are talking about mago-mi, though. Not sure if mago-remote is necessary if mago-mi itself is built as an 64-bit-executable.

The registry key is the way the executable is found, see https://github.com/rainers/mago/blob/master/DebugEngine/MagoNatDE/RemoteDebuggerProxy.cpp#L46. It seems simple to also search a fixed name (magoremote.exe) in the same directory as the invoking exe/dll by extracting the path from GetModuleFileName() or similar. PR welcome ;-)
