### ISSUE TITLE
-break-insert cannot handle double quotes

### ISSUE THREAD

**Issue by andre2007** [rainers/mago#31]
Mago-mi only support -break-insert without double quotes:

Fails:
```
3-break-insert -f "c:\\Develop\\D\\projects\\command-line\\source\\app.d:13"
Invalid breakpoint parameters
```

Succeeds
```
3-break-insert -f c:\\Develop\\D\\projects\\command-line\\source\\app.d:13
```

**Comment by andre2007** [comment]
Maybe here:
https://github.com/rainers/mago/blob/ad43ffe3da4c6c0bd870a83d5e1201fdadc39b39/MagoMI/mago-mi/source/miutils.cpp#L613

s.th. like 
```
if ( s.front() == '"' ) {
    s.erase( 0, 1 ); // erase the first character
    s.erase( s.size() - 1 ); // erase the last character
}
```
needs to be added to remove leading and trailing double quotes.

**Comment by rainers** [comment]
I have added an `unquoteValue` there, please give it a try.

**Comment by andre2007** [comment]
Fantastic, that solved the issue.
(mago-mi has still other issues in Visual Studio Code, but unrelated to quoting)
