### ISSUE TITLE
Strange DataSource->InitDebugInfo call behavior

### ISSUE THREAD

**Issue by buggins** [rainers/mago#6]
I've found that mago-mi now crashes on loading of symbols.
In MagoNatDE Module::LoadSymbols
hr = dataSource->InitDebugInfo( mCoreMod->GetPath(), mCoreMod->GetSymbolSearchPath() );
Instead of DataSource::InitDebugInfo( const wchar_t* filename, const wchar_t* searchPath )
another method InitDebugInfo( IDiaSession* session, IAddressMap* addrMap ) is called.

Not sure what is broken.
Tried both "Debug StaticDE" and "Release StaticDE"

**Comment by rainers** [comment]
`InitDebugInfo( IDiaSession* session, IAddressMap* addrMap )` has been added to the interface. I suspect this is a rebuild problem (due to missing dependencies). Does it also happen after a full rebuild?

**Comment by buggins** [comment]
pulled latest upstream - issue is gone
