### ISSUE TITLE
getting frame docContext is broken : GetVAFromSecOffset result wrong checking

### ISSUE THREAD

**Issue by buggins** [rainers/mago#7]
StackFrame.cpp 
info.Address = (Address64) session->GetVAFromSecOffset( line.Section, line.Offset );if( info.Address )

Current check:
        if( info.Address )
             return E_FAIL;

Fix:
        if( !info.Address )
             return E_FAIL;

**Comment by rainers** [comment]
PR merged.

**Comment by buggins** [comment]
Thank you!
